name: Deploy SDRnow Landing Page

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu-version: latest

      - name: OpenTofu Init
        run: tofu init
        working-directory: ./infra
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_KEY }}
          AWS_REGION: fr-par

      - name: Generate Password Hash
        run: |
          HASH=$(docker run --rm caddy caddy hash-password --plaintext "${{ secrets.STAGING_PASSWORD }}")
          echo "STAGING_PASSWORD_HASH=$HASH" >> $GITHUB_ENV

      - name: OpenTofu Apply
        run: tofu apply -replace="scaleway_instance_server.web" -auto-approve
        working-directory: ./infra
        env:
          SCW_ACCESS_KEY: ${{ secrets.SCW_ACCESS_KEY }}
          SCW_SECRET_KEY: ${{ secrets.SCW_SECRET_KEY }}
          SCW_DEFAULT_PROJECT_ID: ${{ secrets.SCW_DEFAULT_PROJECT_ID }}
          AWS_ACCESS_KEY_ID: ${{ secrets.SCW_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SCW_SECRET_KEY }}
          AWS_REGION: fr-par
          TF_VAR_staging_password_hash: ${{ env.STAGING_PASSWORD_HASH }}
